Add files via upload

diff --git a/jbod_server b/jbod_server
--- a/jbod_server
+++ b/jbod_server
@@ -1,3 +1,34 @@
 #!/bin/bash
 
-LD_LIBRARY_PATH="$LD_LIBRARY_PATH:." ./jbod_server_binary -p "$1"
+verbose=false
+port=""
+
+# Parse command-line options
+while getopts ":vp:" opt; do
+  case $opt in
+    v)
+      verbose=true
+      ;;
+    p)
+      port=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [[ -n $port ]]; then
+  if $verbose; then
+    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:." ./jbod_server_binary -v -p "$port"
+  else
+    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:." ./jbod_server_binary -p "$port"
+  fi
+else
+  echo "No port provided."
+fi
